server:
  port: 8082

spring:
  mail:
    company: godme
    template: 您的验证码是:%s
    subject: 验证码
    host: smtp.qq.com
    port: 587
    username: 664473032@qq.com
    password: xupnptdtrnmvbchd
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
  application:
    name: mail
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://registry1:8761/eureka,http://registry2:8762/eureka
    fetch-registry: true
  instance:
    instance-id: mail
    appname: mail
    ip-address: mail
    prefer-ip-address: true